taskapp/urls.py
from django.urls import path
from . import views
from .views import(
    Task_Create_View,
    Task_Update_View,
    Task_Delete_View
)


app_name ='taskapp'

urlpatterns = [
    path('', views.home, name='home-view'),
    path('create/',Task_Create_View.as_view(),name='task-create'),
    path('update/<int:pk>/',Task_Update_View.as_view(),name='task-update'),
    path('delete/<int:pk>/',Task_Delete_View.as_view(),name='task-delete'),
  
]

taskapp_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('taskapp.urls'))
]

taskapp/models.py
from django.db import models

class Task(models.Model):
    pub_date = models.DateField(auto_now_add=True)
    headline = models.CharField(max_length=200)
    # content = models.TextField()
   
    def __str__(self):
        return self.headline

taskapp/views.py
from django.shortcuts import render,get_object_or_404
from django.urls import reverse_lazy

from .models import Task
from django.views.generic.edit import(
    CreateView,
    UpdateView,
    DeleteView
) 

def home(request):
    task_list = Task.objects.all()
    
    return render(request,'taskapp/homepage.html',{'task_list':task_list})  #'


class Task_Create_View(CreateView):
    model = Task
    fields = ['headline']
    template_name ='taskapp/task_create.html'
    success_url = reverse_lazy("taskapp:home-view")


class Task_Update_View(UpdateView):
    model = Task
    fields = ['headline']
    template_name ='taskapp/task_update.html'
    success_url = reverse_lazy("taskapp:home-view")

class Task_Delete_View(DeleteView):
    model = Task
    # success_url = reverse_lazy('taskapp:home-view')
    success_url = reverse_lazy("taskapp:home-view")

    # def get_object(self):
    #     post =self.kwargs.get("id")
    #     return get_object_or_404(Task,id=post)

taskapp/templates/taskapp/homepage.html
  {%extends 'taskapp/main.html' %}
  
  {% block content %}

  <style>
.custom-css-table{
  margin-top:2%;
}
h1{
  text-align:center;
}
h4{
  text-align:center;
  
}
.add-button-class{
  text-align:center; 
  margin-top: 20px;
}
.primary-key{
  margin-left: 20px;
}
  </style>

<h1 >A simple ''Task App'' with ''Django CRUD''</h1>
<h4>By <a href="https://www.altafhosen.com/"><i>Altaf Hosen</i></a></h4>

 <a  href="{% url 'taskapp:task-create'  %}">
    <div class="add-button-class">
        <button type="button" class="btn btn-success col-6 ">Click to Add</button>
    </div>
</a>

<div class="custom-css-table">
    <table   class="table table-hover ">
        <tbody>
 
            {% for task in task_list %}
               <tr>
               
                 <th scope="col">
                   <div  class="primary-key">
                    <button type="button" class="btn btn-warning">{{task.pk}}</button>
                   </div>
                   
                  </th>

                
                   <th scope="col"> 
                    <a href="{% url 'taskapp:task-update' task.pk %}">
                      <div>
                      <button type="button" class="btn btn-warning">Update</button>
                      </div>
                    </a>
                    </th>
                  
                 
                   <th scope="col">
                     <p>{{ task.headline }}</p>
                   </th>

               
                   <th scope="col">
              <form method="post" action="{% url 'taskapp:task-delete' task.pk %}" >
                  {% csrf_token %}
                  <input class="btn btn-danger" type="submit" value="Delete">
              </form>
            </th>

               </tr>
             {% endfor %}
           </tbody>
         
       </table>
       </div>




  {% endblock %}

taskapp/templates/taskapp/main.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Task App</title>
  </head>
  <body>
    

  {% block content%}

  
  {% endblock %}



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

  </body>
</html>

taskapp/templates/taskapp/task_create.html
{%extends 'taskapp/main.html' %}
  
{% block content %}

<style>
    .custom-css-table{
      margin-top:2%;
    }
    h1{
      text-align:center;
    }
    .add-button-class{
      text-align:center; 
      margin-top: 20px;
    }
 </style>

<a  href="{% url 'taskapp:home-view'  %}">
    <div class="add-button-class">
        <button type="button" class="btn btn-success col-6">Back To Home</button>
    </div>
</a>

    
<form class="add-button-class" method="post" >
    {% csrf_token %}
        {{ form.as_p}}
    <input class="btn btn-success col-6" type="submit" value="Save">
</form>

{% endblock %}

taskapp/templates/taskapp/task_update.html
{%extends 'taskapp/main.html' %}
  
{% block content %}

<style>
    .custom-css-table{
      margin-top:2%;
    }
    h1{
      text-align:center;
    }
    .add-button-class{
      text-align:center; 
      margin-top: 20px;
    }
 </style>

<a  href="{% url 'taskapp:home-view'  %}">
    <div class="add-button-class">
        <button type="button" class="btn btn-success col-6">Back To Home</button>
    </div>
</a>

    
<form class="add-button-class" method="post" >
    {% csrf_token %}
        {{ form.as_p}}
    <input class="btn btn-success col-6" type="submit" value="Save">
</form>


{% endblock %}